### ISSUE TITLE
Error: Plugin Did not Respond

### ISSUE THREAD

**Issue by rogersgt** [cloudposse/terraform-provider-utils#453]
### Describe the Bug

Running Terraform plan, causes the plugin to error with an exit code 1, `panic: assignment to entry in nil map`. From the output message, `This is always indicative of a bug within the plugin`.

### Expected Behavior

Terraform Plan output the following message:
`Error: Plugin did not respond

  with module.cross_region_hub_connector["use2"].data.utils_component_config.config[0],
  on .terraform/modules/cross_region_hub_connector/modules/remote-state/main.tf line 1, in data "utils_component_config" "config":
   1: data "utils_component_config" "config" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more
details.

Error: Plugin did not respond

  with module.iam_roles.module.account_map.data.utils_component_config.config[0],
  on .terraform/modules/iam_roles.account_map/modules/remote-state/main.tf line 1, in data "utils_component_config" "config":
   1: data "utils_component_config" "config" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more
details.

Error: Plugin did not respond

  with module.tgw_hub.data.utils_component_config.config[0],
  on .terraform/modules/tgw_hub/modules/remote-state/main.tf line 1, in data "utils_component_config" "config":
   1: data "utils_component_config" "config" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more
details.

Error: Plugin did not respond

  with module.tgw_hub_role.module.account_map.data.utils_component_config.config[0],
  on .terraform/modules/tgw_hub_role.account_map/modules/remote-state/main.tf line 1, in data "utils_component_config" "config":
   1: data "utils_component_config" "config" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more
details.

Stack trace from the terraform-provider-utils plugin:

panic: assignment to entry in nil map

goroutine 150 [running]:
github.com/cloudposse/atmos/internal/exec.ProcessStacks({{0xc000078090, 0x2f}, {{{0xc001dea2a0, 0x14}, 0x0, {0xc000c330b0, 0x2f}, 0x1, 0x1, 0x1, ...}, ...}, ...}, ...)
	github.com/cloudposse/atmos@v1.122.0/internal/exec/utils.go:438 +0x109d
github.com/cloudposse/atmos/pkg/component.ProcessComponentInStack({0xc0028dfb20?, 0x1e?}, {0xc001dea228?, 0x4?}, {0x0?, 0x4?}, {0x0?, 0x4?})
	github.com/cloudposse/atmos@v1.122.0/pkg/component/component_processor.go:33 +0x1e7
github.com/cloudposse/atmos/pkg/component.ProcessComponentFromContext({0xc0028dfb20, 0x1e}, {0xc001757bfc, 0x4}, {0xc001757c20, 0x4}, {0xc001757bdc, 0x4}, {0xc001757c10, 0x7}, ...)
	github.com/cloudposse/atmos@v1.122.0/pkg/component/component_processor.go:80 +0x3b4
github.com/cloudposse/terraform-provider-utils/internal/provider.dataSourceComponentConfigRead({0x3b9a028?, 0xc0027a0e10?}, 0xc00184ec00, {0x0?, 0x0?})
	github.com/cloudposse/terraform-provider-utils/internal/provider/data_source_component_config.go:121 +0x3fb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0009e2[540](https://github.com/QuicksortRx/qsrx-infra/actions/runs/12280259382/job/34267957429?pr=475#step:3:562), {0x3b9a028, 0xc0027a0e10}, 0xc00184ec00, {0x0, 0x0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/resource.go:823 +0x119
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0009e2540, {0x3b9a028, 0xc0027a0e10}, 0xc00184eb00, {0x0, 0x0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/resource.go:1043 +0x13a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc000a63710, {0x3b9a028?, 0xc0027a0d50?}, 0xc0027a0cf0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/grpc_provider.go:1436 +0x6aa
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc000997860, {0x3b9a028?, 0xc0027a0270?}, 0xc000b86280)
	github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov5/tf5server/server.go:688 +0x26d
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x3449080, 0xc000997860}, {0x3b9a028, 0xc0027a0270}, 0xc00184e980, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:665 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000926800, {0x3b9a028, 0xc0027a01e0}, {0x3ba7740, 0xc000685d40}, 0xc002843d40, 0xc000a6b1d0, 0x598b680, 0x0)
	google.golang.org/grpc@v1.67.1/server.go:1394 +0xe2b
google.golang.org/grpc.(*Server).handleStream(0xc000926800, {0x3ba7740, 0xc000685d40}, 0xc002843d40)
	google.golang.org/grpc@v1.67.1/server.go:1805 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.67.1/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 16
	google.golang.org/grpc@v1.67.1/server.go:1040 +0x125

Error: The terraform-provider-utils plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

exit status 1`

### Steps to Reproduce

I'm using the Cloud Posse ecosystem, with as much boilerplate setup as possible; the method to recreate this issue is simply calling `atmos terraform plan tgw/spoke --stack core-use2-network`

### Environment

Atmos 1.99.0
Using OpenTofu (configured in atmos.yaml) 1.7.1
Terraform 1.6.3 (although should be calling Open Tofu in place of terraform via atmos)

**Comment by rankin-tr** [comment]
+1 I began experiencing this error with v1.27.0 of terraform-provider-utils. 

Atmos 1.47.0
Terraform 1.5.7

**Comment by rankin-tr** [comment]
https://github.com/cloudposse/terraform-provider-utils/pull/458 has resolved this issue for me

**Comment by RoseSecurity** [comment]
@rankin-tr Have you encountered this recently? Starting to see this with Atmos `1.173.0` and `provider registry.terraform.io/cloudposse/utils v1.29.0` intermittently
